# docker-compose.yml
version: '3'
services:
  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_DATABASE=chat_mongo
      - MONGO_INITDB_ROOT_USERNAME=chat
      - MONGO_INITDB_ROOT_PASSWORD=chat
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db